process.env.TZ = "UTC";
import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import userRoutes from "./api/routes/userRoutes.js";
import userManageRoutes from "./api/routes/userManageRoutes.js";
import categoryRoutes from "./api/routes/CategoryRoutes.js";
import productRoutes from "./api/routes/productsRoutes.js";
import attributesRoutes from "./api/routes/attributesRoutes.js";
import attributeValuesRoutes from "./api/routes/attributeValuesRoutes.js";
import variantAttributesRoutes from "./api/routes/variantAttributesRoutes.js";
import variantRoutes from "./api/routes/variantsRoutes.js";
import voucherRoutes from "./api/routes/voucherRoutes.js";
import cartRoutes from "./api/routes/cartRoutes.js";
import orderRoutes from "./api/routes/orderRoutes.js";
import zaloPayRoutes from "./api/ZaloPay/zaloPayRoutes.js";
import shippingRoutes from "./api/GHN/shippingRoutes.js";
import { autoCancelPendingOrders } from ".api/config/AutoZalopay.js";
autoCancelPendingOrders();
dotenv.config();
const app = express();
app.use(cors());
app.use(express.json({ limit: "20mb" }));
app.use(express.urlencoded({ extended: true }));


app.use("/api", userRoutes);
app.use("/api/users", userManageRoutes);
app.use("/api/products", productRoutes);
app.use("/api/categories", categoryRoutes);
app.use("/api/variants", variantRoutes);
app.use("/api/attributes", attributesRoutes);
app.use("/api/attribute-values", attributeValuesRoutes);
app.use("/api/variant-attributes", variantAttributesRoutes);
app.use("/api/vouchers", voucherRoutes);
app.use("/api/cart", cartRoutes);
app.use("/api/orders", orderRoutes);
app.use("/api/payment", zaloPayRoutes);
app.use("/api/shipping", shippingRoutes);
app.get("/check", (req, res) => {
  res.send("ShopThuCong User API is running...");
});
console.log("JWT_SECRET:", process.env.JWT_SECRET);
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`Server chạy tại cổng ${PORT}`));
